name: Plan / Test On PR 

on:
  pull_request:
    branches:
      - master
jobs:  
  plan:
    name: Plan
    runs-on: ubuntu-20.04
    permissions: write-all
    strategy:
      matrix:
        path: 
          - pushmetrics.io
          - query.me
    steps:
      - name: Publish terraform plan result into PR
        uses: dasmeta/reusable-actions-workflows@0.1.1
        with:
          fetch-depth: 100
          paths: terraform/${{ matrix.path }}
          path: ${{ matrix.path }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETE_ID }}
          backend: true
          backend-config: backend_prod.hcl 
          var-file: prod.tfvars