name: Publish terraform plan result into PR
description: "Helo Publish PR comment in Marketplacee from terraform plan"
author: Das Meta
branding:
  icon: globe
  color: purple
inputs:
  github-token:
    description: "GitHub token for commenting on PRs. Defaults to using 'secrets.GITHUB_TOKEN'"
    required: false
  fetch-depth: 
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    required: false
    default: ""
  aws-region: 
    description: "AWS Region, e.g. us-east-2"
    required: false
    default: us-east-1
  aws-access-key-id: 
    description: "AWS Access Key ID. This input is required if running in the GitHub hosted environment."
    required: false 
  aws-secret-access-key:
    description: "AWS Secret Access Key. This input is required if running in the GitHub hosted environment."
    required: false
  path:
    description: "This is for file that plan will redirect into it like plan.txt"
    required: false
    default: folder1
  backend:
    description: "Disable or Enable Backend"
    required: false
    default: "false"
  backend-config:
    description: "Configuration to be merged with what is in the configuration file's 'backend' block."
    required: false
    default: "backend.hcl"
  var-file:
    description: "Variable file"
    required: false
    default: "env.tfvars"
  post-plan-to-github-pr:
    description: "Allows to disable plan result posting into github PR as comment"
    required: false
    default: "true"
  do-apply:
    description: "Allows to enable plan result direct apply"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - uses: marceloprado/has-changed-path@v1
      id: changed
      with:
        paths: ${{ inputs.path }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws-region }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.1

    - name: Initialize Terraform
      # continue-on-error: true
      run: |
        pwd
        ls -hla
        echo $PWD
        cd ${{ inputs.path }}
        terraform init -backend="${{inputs.backend}}" -backend-config="${{inputs.backend-config}}"
      shell: bash

    - name: Plan Terraform
      id: plan
      # continue-on-error: true
      run: |
        cd ${{ inputs.path }}
        terraform plan -var-file="${{inputs.var-file}}" -no-color -out=plan.tfplan \
        && terraform show -no-color plan.tfplan
      shell: bash

    - run: echo '${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}' | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > ${{inputs.path}}/plan.txt
      shell: bash

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: ${{inputs.path}}/plan.tfplan
    #     path: ${{inputs.path}}/plan.tfplan

    - name: Put Plan Files in ENV Vars
      run: |
        PLAN=$(cat ${{inputs.path}}/plan.txt)
        echo "PLAN<<EOF" >> $GITHUB_ENV
        echo "$PLAN" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - name: Post Plan to GitHub PR
      if: ${{inputs.post-plan-to-github-pr == 'true'}}
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: ${{ inputs.github-token }}
        allow-repeats: true
        repo-token-user-login: 'github-actions[bot]'
        message: |
            ## Plan Output
           
            ```diff
            ${{ env.PLAN }}
            ```
            
            Merge to master to apply all of the above

    - name: Apply Terraform
      if: ${{inputs.do-apply == 'true'}}
      id: apply
      run: |
        cd ${{ inputs.path }}
        terraform apply -var-file="${{inputs.var-file}}" -no-color plan.tfplan
      shell: bash
