name: Tflint
description: "terraform tool"
author: Das Meta
branding:
  icon: globe
  color: purple
inputs:
  fetch-depth: 
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    required: false
    default: 0
  path:
    description: "Path where will run checkov"
    required: false
    default: modules/dashboard
  aws-region: 
    description: "AWS Region, e.g. us-east-2"
    required: false
    default: us-east-1
  aws-access-key-id: 
    description: "AWS Access Key ID. This input is required if running in the GitHub hosted environment."
    required: false 
  aws-secret-access-key:
    description: "AWS Secret Access Key. This input is required if running in the GitHub hosted environment."
    required: false
  github-token:
    description: "Path where will run checkov"
    required: false
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws-region }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.1

    - name: Terraform init
      run: |
          cd ${{ inputs.path}}
          terraform init
      shell: bash

    - name: Setup TFLint
      run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      shell: bash
    
    - name: Show version
      run: tflint --version
      shell: bash

    - name: Init TFLint
      id: tflint
      run: |
          cd ${{inputs.path}}
          tflint
          echo tflint --enable-rule=terraform_unused_declarations
      shell: bash
      continue-on-error: true
