name: Plan and Apply
on:
  pull_request:
    types: [closed]
    branches:
      - master
    paths:
      - 'terraform/project1/**'
      - 'terraform/project2/**'
jobs:
  plan:
    name: Plan and apply stage
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        path:
          - project1
          - project2
    steps:
      - name: Plan stage ${{ matrix.path }}
        uses: dasmeta/reusable-actions-workflows/terraform@0.0.4
        with:
          post-plan-to-github-pr: 'false'
          do-apply: 'true'
          fetch-depth: 100
          path: terraform/${{ matrix.path }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          backend: true
          backend-config: stage.tfbackend
          var-file: stage.tfvars
