name: Infracost
description: "shows cloud cost estimates for Terraform."
author: Das Meta
branding:
  icon: globe
  color: purple
inputs:
  fetch-depth: 
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    required: false
    default: 0
  api-key:
    description: "Your Infracost API key"
    required: false
  path:
    description: "The path where will run this job"
    required: false
  token:
    description: "Yout github token"
    required: false
runs:
  using: "composite"
  steps:  
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.pull_request.base.ref }}'
          fetch-depth: 0
      
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ inputs.api-key }}

      - name: Infracost Breakdown
        run: |
            infracost breakdown --path ${{inputs.path}} --format=json --out-file=${{inputs.path}}.json
          
      - name: Post Infracost comment
        run: |
            infracost comment github  --path=${{inputs.path}}.json \
                                      --repo=$GITHUB_REPOSITORY \
                                      --github-token=${{inputs.token}} \
                                      --pull-request=${{github.event.pull_request.number}} \
                                      --behavior=update
