name: Checkov
description: "terraform tool"
author: Das Meta
branding:
  icon: globe
  color: purple
inputs:
  fetch-depth: 
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    required: false
    default: 0
  directory:
    description: "Path where will run checkov"
    required: false
    default: modules/dashboard
  github-token:
    description: "Path where will run checkov"
    required: false
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.1
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Test with Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ${{ inputs.directory }}
        framework: terraform 
        download_external_modules: true
      continue-on-error: true
    
    - run: echo '${{ steps.checkov.outputs.stdout || steps.checkov.outputs.stderr }}' | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > ${{ inputs.directory }}/checkov.txt
      shell: bash

    - name: Put Files in ENV Vars
      run: |
        CHECKOV=$(cat ${{ inputs.directory }}/checkov.txt)
        echo "CHECKOV<<EOF" >> $GITHUB_ENV
        echo "$CHECKOV" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - name: Post to GitHub PR
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: ${{ inputs.github-token }}
        allow-repeats: true
        repo-token-user-login: 'github-actions[bot]'
        message: |
          ${{env.CHECKOV}}