on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: self test action
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
